pipeline_name: dp_realworld_image
# env
env_name: realworld_image
abs_action: false
dataset_path: data/frankaslide.hdf5
mode: train
max_episode_steps: 400
render_obs_key: 'agentview_image'
shape_meta:
  action:
    shape:
    - 7
  obs:
    agentview:
      shape:
      - 3
      - 224
      - 224
      type: rgb
    ee_pose:
      shape:
      - 3
      type: low_dim
    ee_quat:
      shape:
      - 4
      type: low_dim
    gripper_state:
      shape:
      - 1
      type: low_dim
action_dim: 7
obs_steps: 2
action_steps: 4

# obs_encoder
rgb_model: resnet18
resize_shape: null
crop_shape:
  - 224
  - 224
random_crop: false
use_group_norm: true
use_seq: true

# train
device: cuda:0
seed: 0
gradient_steps: 500000
batch_size: 64
horizon: 5
nn: chi_transformer # or chi_unet or dit
diffusion: ddpm
sample_steps: 50
temperature: 1.0
diffusion_x: true
extra_sample_steps: 8

# optimizer
lr: 0.0001

# log
exp_name: ${env_name}_${diffusion}_${nn}
save_path: logs
project: tactile-rep
group: dp_realworld_image
wandb_mode: online
log_freq: 2000
save_freq: 20000
log_dir: logs

# hydra
hydra:
  job:
    chdir: false
  run:
    dir: ${log_dir}/${pipeline_name}/${env_name}/hydra/${seed}
  output_subdir: null
