pipeline_name: dbc_realworld_image

# env
env_name: realworld_image_eef_pos
abs_action: false
dataset_path: data/frankaslide_tactile.hdf5
mode: train
max_episode_steps: 400

shape_meta:
  action:
    shape:
    - 3
  obs:
    agentview:
      shape:
      - 3
      - 224
      - 224
      type: rgb
    ee_pos:
      shape:
      - 3
      type: low_dim

action_dim: 3
obs_steps: 1
action_steps: 1

# diffusion
diffusion: edm
solver: ${solvers.${diffusion}}
solvers:
  ddpm: null
  edm: euler
  sde: ode_dpmsolver++_2M
  csde: ode_dpmsolver++_2M

# obs_encoder
rgb_model: resnet18
resize_shape: null
crop_shape:
  - 224
  - 224
random_crop: false
use_group_norm: true
use_seq: true

# train
device: cuda:0
seed: 0
gradient_steps: 250000
batch_size: 128
horizon: 2
nn: dit
sample_steps: 50
temperature: 1.0
diffusion_x: false
extra_sample_steps: 8

# optimizer
lr: ${lrs.${nn}}
lrs:
  dit: 0.0001
  pearce_mlp: 0.001

# log
exp_name: ${env_name}_${diffusion}_${nn}
save_path: logs
project: tactile-rep
group: dbc_realworld_image
wandb_mode: online
log_freq: 5000
save_freq: 50000
log_dir: logs

# eval
model_path: ckpt/edm_dit_image/model_320000.pt # ckpt/edm_pearce_image/model_500000.pt

# hydra
hydra:
  job:
    chdir: false
  run:
    dir: ${log_dir}/${pipeline_name}/${env_name}/hydra/${seed}
  output_subdir: null
